#include 'tlpp-core.th'
#include 'tlpp-rest.th'

@Get("/test/helloWorld")
Function u_helloWorld()
  Local cReturn := "Meu primeiro REST em TL++ " as character
  oRest:setResponse(cReturn)
Return .T.


@Get("sample/rest/crud/query")
function u_getQueryUser()
  local cUser   := ''
  local jQuery  := jsonObject():New()

  jQuery := oRest:getQueryRequest()

  if ( jQuery <> Nil )
    cUser := jQuery[ 'user' ]
  endif

  processGetUser( cUser )
return 
